[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs_20", "yarn"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build"
]

[phases.start]
cmd = "php -d memory_limit=-1 -S 0.0.0.0:${PORT:-8000} -t public/"

[variables]
APP_ENV = "production"
APP_DEBUG = "false"
CACHE_DRIVER = "file"
SESSION_DRIVER = "cookie"
QUEUE_CONNECTION = "sync"

[static]
# Serve public directory
guest = "."
